### ISSUE TITLE
Exception when trying to create new user

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#56]
Currently our notifo instance is throwing an exception "System.InvalidOperationException" when trying to create a user via API.
see stack trace:

```
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)

at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)

at Notifo.Domain.Users.UpdateUser.ExecuteAsync(User user, IServiceProvider serviceProvider, CancellationToken ct) in /src/src/Notifo.Domain/Users/UpdateUser.cs:line 140

at Notifo.Domain.Users.UserStore.<>c__DisplayClass14_0.<<UpsertAsync>b__0>d.MoveNext() in /src/src/Notifo.Domain/Users/UserStore.cs:line 157
--- End of stack trace from previous location ---
at Notifo.Infrastructure.Updater.UpdateRetriedAsync[T](Int32 numRetries, Func1 action)

at Notifo.Areas.Api.Controllers.Users.UsersController.PostUsers(String appId, UpsertUsersDto request) in /src/src/Notifo/Areas/Api/Controllers/Users/UsersController.cs:line 189

at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

"Error message": "No service for type 'Notifo.Domain.Utils.IApiKeyGenerator' has been registered."

Updating users is still working.

**Comment by SebastianStehle** [comment]
Thx, will have a look asap.
