### ISSUE TITLE
TokenRefreshManager Exception

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#61]
Hi,
since one of the last builds - 360/361, I get lots of exceptions for action "HandleJob".
It looks like there is an issue in receiving new push tokens. I attached the stack trace:
```
   at Google.Apis.Auth.OAuth2.TokenRefreshManager.GetAccessTokenForRequestAsync(CancellationToken cancellationToken)
   at Google.Apis.Auth.OAuth2.ServiceAccountCredential.GetAccessTokenForRequestAsync(String authUri, CancellationToken cancellationToken)
   at Google.Apis.Auth.OAuth2.ServiceCredential.GetAccessTokenWithHeadersForRequestAsync(String authUri, CancellationToken cancellationToken)
   at Google.Apis.Auth.OAuth2.ServiceCredential.InterceptAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Google.Apis.Http.ConfigurableMessageHandler.CredentialInterceptAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Google.Apis.Http.ConfigurableMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at FirebaseAdmin.Util.ErrorHandlingHttpClient`1.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at FirebaseAdmin.Util.ErrorHandlingHttpClient`1.SendAndReadAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at FirebaseAdmin.Util.ErrorHandlingHttpClient`1.SendAndDeserializeAsync[TResult](HttpRequestMessage request, CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessagingClient.SendAsync(Message message, Boolean dryRun, CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessaging.SendAsync(Message message, Boolean dryRun, CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessaging.SendAsync(Message message, CancellationToken cancellationToken)
   at Notifo.Domain.Integrations.Firebase.FirebaseMobilePushSender.SendAsync(UserNotification userNotification, MobilePushOptions options, CancellationToken ct) in /src/src/Notifo.Domain.Integrations/Firebase/FirebaseMobilePushSender.cs:line 48
   at Notifo.Domain.Channels.MobilePush.MobilePushChannel.SendCoreAsync(MobilePushJob job, UserNotification notification, App app, List`1 senders, CancellationToken ct) in /src/src/Notifo.Domain/Channels/MobilePush/MobilePushChannel.cs:line 267
   at Notifo.Domain.Channels.MobilePush.MobilePushChannel.SendAsync(MobilePushJob job, CancellationToken ct) in /src/src/Notifo.Domain/Channels/MobilePush/MobilePushChannel.cs:line 249
   at Notifo.Domain.Channels.MobilePush.MobilePushChannel.HandleAsync(MobilePushJob job, Boolean isLastAttempt, CancellationToken ct) in /src/src/Notifo.Domain/Channels/MobilePush/MobilePushChannel.cs:line 200
   at Notifo.Infrastructure.Scheduling.Implementation.DelegatingScheduleHandler`1.OnSuccessAsync(List`1 jobs, Boolean isLastAttempt, CancellationToken ct) in /src/src/Notifo.Infrastructure/Scheduling/Implementation/DelegatingScheduleHandler.cs:line 43
   at Notifo.Infrastructure.Scheduling.Implementation.TimerBased.TimerConsumer`1.HandleAsync(SchedulerBatch`1 document) in /src/src/Notifo.Infrastructure/Scheduling/Implementation/TimerBased/TimerConsumer.cs:line 160
```

**Comment by SebastianStehle** [comment]
Where is the exception for the stack trace? It looks more like firebase cannot authenticate.

**Comment by CR4567** [comment]
exception message is only "A task was canceled"
I was also wondering why it's in the OAuth2 namespace. 
Is it using a refreshToken mechanism? So could be an issue with requesting a valid token?

**Comment by SebastianStehle** [comment]
I have no idea how it works, I just use the SDK.

**Comment by SebastianStehle** [comment]
It seems to a normal timeout. The default is 4sec here so I am not sure if it should be changed.

**Comment by CR4567** [comment]
I understand that. I'm just wondering why it suddenly occurred. Until this update I've never seen that. 
Maybe I can also see something on firebase console.
