### ISSUE TITLE
Exception when sending WebPush

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#75]
Currently, I get some "A task was canceled" exceptions when sending WebPush Messages.
Is this related to the change of the exception handling in the last build?

```
 at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at WebPush.WebPushClient.SendNotificationAsync(PushSubscription subscription, String payload, Dictionary`2 options, CancellationToken cancellationToken)
   at Notifo.Domain.Channels.WebPush.WebPushChannel.SendCoreAsync(WebPushJob job, CancellationToken ct) in /src/src/Notifo.Domain/Channels/WebPush/WebPushChannel.cs:line 191
   at Notifo.Domain.Channels.WebPush.WebPushChannel.SendAsync(WebPushJob job, CancellationToken ct) in /src/src/Notifo.Domain/Channels/WebPush/WebPushChannel.cs:line 160
   at Notifo.Domain.Channels.WebPush.WebPushChannel.HandleAsync(WebPushJob job, Boolean isLastAttempt, CancellationToken ct) in /src/src/Notifo.Domain/Channels/WebPush/WebPushChannel.cs:line 139
   at Notifo.Infrastructure.Scheduling.Implementation.DelegatingScheduleHandler`1.OnSuccessAsync(List`1 jobs, Boolean isLastAttempt, CancellationToken ct) in /src/src/Notifo.Infrastructure/Scheduling/Implementation/DelegatingScheduleHandler.cs:line 43
   at Notifo.Infrastructure.Scheduling.Implementation.TimerBased.TimerConsumer`1.HandleAsync(SchedulerBatch`1 document) in /src/src/Notifo.Infrastructure/Scheduling/Implementation/TimerBased/TimerConsumer.cs:line 160
```

**Comment by SebastianStehle** [comment]
There is no exception, you should not only send the stacktrace only ;)

**Comment by CR4567** [comment]
my fault, but there is not much more information:
```
action: "HandleJob"
exception: {
message: "A task was canceled."
stackTrace: "   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at WebPush.WebPushClient.SendNotificationAsync(PushSubscription subscription, String payload, Dictionary`2 options, CancellationToken cancellationToken)
   at Notifo.Domain.Channels.WebPush.WebPushChannel.SendCoreAsync(WebPushJob job, CancellationToken ct) in /src/src/Notifo.Domain/Channels/WebPush/WebPushChannel.cs:line 191
   at Notifo.Domain.Channels.WebPush.WebPushChannel.SendAsync(WebPushJob job, CancellationToken ct) in /src/src/Notifo.Domain/Channels/WebPush/WebPushChannel.cs:line 160
   at Notifo.Domain.Channels.WebPush.WebPushChannel.HandleAsync(WebPushJob job, Boolean isLastAttempt, CancellationToken ct) in /src/src/Notifo.Domain/Channels/WebPush/WebPushChannel.cs:line 139
   at Notifo.Infrastructure.Scheduling.Implementation.DelegatingScheduleHandler`1.OnSuccessAsync(List`1 jobs, Boolean isLastAttempt, CancellationToken ct) in /src/src/Notifo.Infrastructure/Scheduling/Implementation/DelegatingScheduleHandler.cs:line 43
   at Notifo.Infrastructure.Scheduling.Implementation.TimerBased.TimerConsumer`1.HandleAsync(SchedulerBatch`1 document) in /src/src/Notifo.Infrastructure/Scheduling/Implementation/TimerBased/TimerConsumer.cs:line 160"
type: "System.Threading.Tasks.TaskCanceledException"
}
```

**Comment by SebastianStehle** [comment]
Thats a normal timeout. Can happen all the time and is normal.

**Comment by CR4567** [comment]
ok was just wondering why this is increased a lot from today on.
<img width="953" alt="Bildschirmfoto 2021-12-15 um 17 30 23" src="https://user-images.githubusercontent.com/10132368/146225846-fbc0c76b-1c0d-4e09-9835-b1d01e9582b6.png">

**Comment by SebastianStehle** [comment]
I don't know. I have not changed anything here. I just had issues with NPM, sometimes external services are also not stable.
