### ISSUE TITLE
Cannot start due to mongodb error

### ISSUE THREAD

**Issue by heromiyo** [notifo-io/notifo#97]
"MongoDbTemplateRepository",
    "MongoDbTopicRepository",
    "MongoDbUserNotificationRepository",
    "MongoDbUserRepository",
    "MongoDbUserStore",
    "MongoDbXmlRepository",
    "MongoGridFsAssetStore",
    "SchedulingConsumer\u00602",
    "SchedulingConsumer\u00602",
    "SchedulingProducer\u00601",
    "SchedulingProducer\u00601",
    "TimerScheduler(messaging)",
    "TimerScheduler(mobilepush)",
    "TimerScheduler(UserNotifications)",
    "TimerScheduler(webhook)",
    "TimerScheduler(webpush)",
    "Providers(messaging)",
    "Providers(mobilepush)",
    "Providers(webhook)",
    "Providers(webpush)",
    "UserCreator",
    "UserNotificationService"
  ],
  "timestamp": "2022-01-19T06:20:59Z",
  "severity": "INFO"
}

{
  "logLevel": "Information",
  "initializedSystem": "ValidationInitializer",
  "timestamp": "2022-01-19T06:20:59Z",
  "severity": "INFO"
}

{
  "logLevel": "Information",
  "initializedSystem": "IntegrationManager",
  "timestamp": "2022-01-19T06:20:59Z",
  "severity": "INFO"
}

Unhandled exception. Squidex.Hosting.Configuration.ConfigurationException: MongoDb connection failed to connect to database Notifications.

 ---> System.TimeoutException: A timeout occurred after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/localhost:27017" }", EndPoint: "Unspecified/localhost:27017", ReasonChanged: "Heartbeat", State: "Disconnected", ServerVersion: , TopologyVersion: , Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server.
 ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConnectAsync(Socket socket, EndPoint endPoint, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConnectAsync(Socket socket, EndPoint endPoint, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.TrySetException(Object exceptionObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConnectAsync(Socket socket, EndPoint endPoint, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.TrySetException(Object exceptionObject)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessSyncEventOrGetAsyncEvent(SocketAsyncContext context, Boolean skipAsyncEvents, Boolean processAsyncEvents)
   at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
--- End of stack trace from previous location ---
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConnectAsync(Socket socket, EndPoint endPoint, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.ServerMonitor.InitializeConnectionAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)", LastHeartbeatTimestamp: "2022-01-19T06:21:29.1065330Z", LastUpdateTimestamp: "2022-01-19T06:21:29.1065334Z" }] }.
   at MongoDB.Driver.Core.Clusters.Cluster.ThrowTimeoutException(IServerSelector selector, ClusterDescription description)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedAsync(IServerSelector selector, ClusterDescription description, Task descriptionChangedTask, TimeSpan timeout, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Clusters.Cluster.SelectServerAsync(IServerSelector selector, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupportedAfterSeverSelctionAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupportedAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.StartImplicitSessionAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoIndexManagerBase`1.CreateOneAsync(CreateIndexModel`1 model, CreateOneIndexOptions options, CancellationToken cancellationToken)
   at Notifo.Domain.Apps.MongoDb.MongoDbAppRepository.SetupCollectionAsync(IMongoCollection`1 collection, CancellationToken ct) in /src/src/Notifo.Domain/Apps/MongoDb/MongoDbAppRepository.cs:line 46
   at Notifo.Infrastructure.MongoDb.MongoDbRepository`1.InitializeAsync(CancellationToken ct) in /src/src/Notifo.Infrastructure/MongoDb/MongoDbRepository.cs:line 96
   --- End of inner exception stack trace ---
   at Notifo.Infrastructure.MongoDb.MongoDbRepository`1.InitializeAsync(CancellationToken ct) in /src/src/Notifo.Infrastructure/MongoDb/MongoDbRepository.cs:line 102
   at Squidex.Hosting.InitializerHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Notifo.Program.Main(String[] args) in /src/src/Notifo/Program.cs:line 19

**Comment by heromiyo** [comment]
now error changed to this 

{
  "logLevel": "Error",
  "message": "An error occurred while reading the key ring.",
  "eventId": {
    "id": 48,
    "name": "ErrorOccurredWhileReadingKeyRing"
  },
  "timestamp": "2022-01-19T06:41:18Z",
  "severity": "ERROR",
  "category": "Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider",
  "exception": {
    "type": "System.TimeoutException",
    "message": "A timeout occurred after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient\u002BAreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : \u00221\u0022, Type : \u0022Unknown\u0022, State : \u0022Disconnected\u0022, Servers : [{ ServerId: \u0022{ ClusterId : 1, EndPoint : \u0022Unspecified/localhost:27017\u0022 }\u0022, EndPoint: \u0022Unspecified/localhost:27017\u0022, ReasonChanged: \u0022Heartbeat\u0022, State: \u0022Disconnected\u0022, ServerVersion: , TopologyVersion: , Type: \u0022Unknown\u0022, HeartbeatException: \u0022MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server.\n ---\u003E System.Net.Sockets.SocketException (99): Cannot assign requested address\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)\n   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)\n   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)\n   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConnectAsync(Socket socket, EndPoint endPoint, CancellationToken cancellationToken)\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine\u0026 stateMachine)\n   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConnectAsync(Socket socket, EndPoint endPoint, CancellationToken cancellationToken)\n   at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder\u00601.AsyncStateMachineBox\u00601.MoveNext(Thread threadPoolThread)\n   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)\n   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)\n   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)\n   at System.Threading.Tasks.Task.TrySetException(Object exceptionObject)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder\u00601.SetException(Exception exception, Task\u00601\u0026 taskField)\n   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConnectAsync(Socket socket, EndPoint endPoint, CancellationToken cancellationToken)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder\u00601.AsyncStateMachineBox\u00601.MoveNext(Thread threadPoolThread)\n   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)\n   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)\n   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)\n   at System.Threading.Tasks.Task.TrySetException(Object exceptionObject)\n   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.\u003C\u003Ec.\u003C.cctor\u003Eb__4_0(Object state)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action\u00601 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow)\n   at System.Net.Sockets.SocketAsyncContext.OperationQueue\u00601.ProcessSyncEventOrGetAsyncEvent(SocketAsyncContext context, Boolean skipAsyncEvents, Boolean processAsyncEvents)\n   at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)\n   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()\n   at System.Threading.ThreadPoolWorkQueue.Dispatch()\n--- End of stack trace from previous location ---\n   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConnectAsync(Socket socket, EndPoint endPoint, CancellationToken cancellationToken)\n   at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)\n   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)\n   --- End of inner exception stack trace ---\n   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)\n   at MongoDB.Driver.Core.Servers.ServerMonitor.InitializeConnectionAsync(CancellationToken cancellationToken)\n   at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)\u0022, LastHeartbeatTimestamp: \u00222022-01-19T06:41:18.2094442Z\u0022, LastUpdateTimestamp: \u00222022-01-19T06:41:18.2094444Z\u0022 }] }.",
    "stackTrace": "   at MongoDB.Driver.Core.Clusters.Cluster.ThrowTimeoutException(IServerSelector selector, ClusterDescription description)\n   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)\n   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChanged(IServerSelector selector, ClusterDescription description, Task descriptionChangedTask, TimeSpan timeout, CancellationToken cancellationToken)\n   at MongoDB.Driver.Core.Clusters.Cluster.SelectServer(IServerSelector selector, CancellationToken cancellationToken)\n   at MongoDB.Driver.MongoClient.AreSessionsSupportedAfterServerSelection(CancellationToken cancellationToken)\n   at MongoDB.Driver.MongoClient.AreSessionsSupported(CancellationToken cancellationToken)\n   at MongoDB.Driver.MongoClient.StartImplicitSession(CancellationToken cancellationToken)\n   at MongoDB.Driver.OperationExecutor.StartImplicitSession(CancellationToken cancellationToken)\n   at MongoDB.Driver.MongoCollectionImpl\u00601.UsingImplicitSession[TResult](Func\u00602 func, CancellationToken cancellationToken)\n   at MongoDB.Driver.MongoCollectionImpl\u00601.FindSync[TProjection](FilterDefinition\u00601 filter, FindOptions\u00602 options, CancellationToken cancellationToken)\n   at MongoDB.Driver.FindFluent\u00602.ToCursor(CancellationToken cancellationToken)\n   at MongoDB.Driver.IAsyncCursorSourceExtensions.ToList[TDocument](IAsyncCursorSource\u00601 source, CancellationToken cancellationToken)\n   at Notifo.Identity.MongoDb.MongoDbXmlRepository.GetAllElements() in /src/src/Notifo.Identity/MongoDb/MongoDbXmlRepository.cs:line 33\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)"
  }
}

{
  "logLevel": "Information",
  "initialize": [
    "ValidationInitializer",
    "IntegrationManager",
    "MongoDbAppRepository",
    "MongoDbEventRepository",
    "MongoDbLogRepository",
    "MongoDbMediaRepository",
    "MongoDbRoleStore",
    "MongoDbSubscriptionRepository",
    "MongoDbTemplateRepository",
    "MongoDbTopicRepository",
    "MongoDbUserNotificationRepository",
    "MongoDbUserRepository",
    "MongoDbUserStore",
    "MongoDbXmlRepository",
    "MongoGridFsAssetStore",
    "SchedulingConsumer\u00602",
    "SchedulingConsumer\u00602",
    "SchedulingProducer\u00601",
    "SchedulingProducer\u00601",
    "TimerScheduler(messaging)",
    "TimerScheduler(mobilepush)",
    "TimerScheduler(UserNotifications)",
    "TimerScheduler(webhook)",
    "TimerScheduler(webpush)",
    "Providers(messaging)",
    "Providers(mobilepush)",
    "Providers(webhook)",
    "Providers(webpush)",
    "UserCreator",
    "UserNotificationService"
  ],
  "timestamp": "2022-01-19T06:41:18Z",
  "severity": "INFO"
}

{
  "logLevel": "Information",
  "initializedSystem": "ValidationInitializer",
  "timestamp": "2022-01-19T06:41:18Z",
  "severity": "INFO"
}

{
  "logLevel": "Information",
  "initializedSystem": "IntegrationManager",
  "timestamp": "2022-01-19T06:41:18Z",
  "severity": "INFO"
}

**Comment by SebastianStehle** [comment]
Hi, how do you start it? With docker compose?

**Comment by heromiyo** [comment]
@SebastianStehle yes with this docker-compose 

version: '2.3'
services:
  NOTIFO_mongo:
    image: mongo:5.0.5
    volumes:
      - /etc/notifo/mongo/db:/data/db
    networks:
      - internal
    restart: unless-stopped

  NOTIFO_notifo:
    image: "squidex/notifo"
    ports:
      - "8880:80"
    environment:
      - URLS__BASEURL=https://${NOTIFO_DOMAIN}
      - STORE__MONGODB__CONFIGURATION=mongodb://notifo_mongo
      - IDENTITY__GOOGLECLIENT=${NOTIFO_GOOGLECLIENT}
      - IDENTITY__GOOGLESECRET=${NOTIFO_GOOGLESECRET}
      - IDENTITY__GITHUBCLIENT=${NOTIFO_GITHUBCLIENT}
      - IDENTITY__GITHUBSECRET=${NOTIFO_GITHUBSECRET}
      - IDENTITY__MICROSOFTCLIENT=${NOTIFO_MICROSOFTCLIENT}
      - IDENTITY__MICROSOFTSECRET=${NOTIFO_MICROSOFTSECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthz"]
      start_period: 60s
    depends_on:
      - NOTIFO_mongo
    volumes:
      - /etc/notifo/assets:/app/Assets
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    driver: bridge

**Comment by SebastianStehle** [comment]
This one is correct: https://github.com/notifo-io/notifo/blob/main/deployment/docker-compose/docker-compose.yml

The env variable for mongodb should be: https://github.com/notifo-io/notifo/blob/main/deployment/docker-compose/docker-compose.yml

**Comment by heromiyo** [comment]
yep works thanks
